# Generated by Django 4.1.5 on 2023-02-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protein_id", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=140)),
                ("start", models.IntegerField()),
                ("stop", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DomainProteinLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="biodata.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxa_id", models.IntegerField()),
                ("clade", models.CharField(default="E", max_length=1)),
                ("genus", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PFam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_id", models.CharField(max_length=20)),
                ("domain_description", models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protein_id", models.CharField(max_length=256)),
                ("sequence", models.CharField(max_length=256, null=True)),
                ("length", models.IntegerField(null=True)),
                (
                    "domain",
                    models.ManyToManyField(
                        through="biodata.DomainProteinLink", to="biodata.domain"
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy",
                        to="biodata.organism",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="domainproteinlink",
            name="protein",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="biodata.protein"
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="pfam_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pfam_id",
                to="biodata.pfam",
            ),
        ),
    ]
